# Generated by Django 2.2 on 2019-04-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('remind', models.BooleanField(default=False)),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='most_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='notification_send',
            field=models.BooleanField(default=False),
        ),
    ]
